stages:
  - test

test_job:
  stage: test
  image: python:3.9
  script:
    - pip install robotframework
    - set PYTHONPATH=%CD%
    - robot HLK.robot
  artifacts:
    paths:
      - log.html
      - output.xml
      - report.html
    expire_in: 1 week