name: RF and CANoe CI with Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 使用你的 JIAHUILI Runner

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 安装 Python 依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 运行本地测试脚本
    - name: Run Robot Framework tests
      run: |
        run_robot.bat  # 直接运行批处理文件

    # 上传测试报告
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          04_logs/output.xml
          04_logs/log.html
          04_logs/report.html  # 根据实际报告路径调整
