name: RF and CANoe CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 安装 Python 依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 运行 Robot Framework 测试
    - name: Run Robot Framework tests
      run: |
        robot tests/test_suite.robot
      env:
        CANOE_PATH: "C:\\Program Files\\Vector CANoe\\CANoe32.exe"

    # 上传测试报告
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          output.xml
          log.html
          report.html
