name: RF and CANoe CI with Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 使用你的 JIAHUILI Runner

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false  # 禁用子模块检查

    # 运行 Robot Framework 测试
    - name: Run Robot Framework tests
      run: cmd.exe /c robot "C:\RfGithub\HLK.robot"
      shell: cmd
      
      
    - name: Run Robot Framework tests
      run: |
        set TIMESTAMP=%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%_%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%
        set TIMESTAMP=%TIMESTAMP: =0%
        mkdir run_%TIMESTAMP%
        copy "C:\RfGithub\HLK.robot" run_%TIMESTAMP%
        cd run_%TIMESTAMP%
        robot HLK.robot > run.log 2>&1
        cd ..
        copy run_%TIMESTAMP%\output.xml .
        copy run_%TIMESTAMP%\log.html .
        copy run_%TIMESTAMP%\report.html .
      shell: cmd


    # 上传测试报告
 #   - name: Upload test results
  #    if: always()
  #    uses: actions/upload-artifact@v4
  #    with:
  #      name: test-results
   #     path: |
   #       "C:\RfGithub\output.xml"
   #       "C:\RfGithub\log.html"
   #       "C:\RfGithub\report.html"
          
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          output.xml
          log.html
          report.html
          run.log