name: RF and CANoe CI with Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 使用你的 JIAHUILI Runner

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: false  # 禁用子模块检查

    # 运行 Robot Framework 测试
    - name: Run Robot Framework tests
      run: |
        echo Current directory: %CD%
        dir
        copy "C:\RfGithub\HLK.robot" .
        robot HLK.robot
      shell: cmd

    # 上传测试报告
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          output.xml
          log.html
          report.html