name: RF and CANoe CI with Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted  # 使用你的 JIAHUILI Runner

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 运行 Robot Framework 测试
    - name: Run Robot Framework tests
      run: cmd.exe /c robot "C:\RfGithub\HLK.robot"
      shell: cmd

    # 上传测试报告
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          "C:\RfGithub\output.xml"
          "C:\RfGithub\log.html"
          "C:\RfGithub\report.html"  # 根据实际报告路径调整